//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int materialId { get; set; }
        public Nullable<int> conductorId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fechaDeEntrega { get; set; }
        public Nullable<System.DateTime> fechaDeDevolucion { get; set; }
    
        public virtual Conductor Conductor { get; set; }
    }
}
